# Generated by Django 6.0.3 on 2026-08-05 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_remove_staff'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('student', 'Student'), ('teacher', 'Teacher'), ('admin', 'Admin'), ('applicant', 'Applicant'), ('finance_officer', 'Finance Officer')], max_length=30),
        ),
    ]
