# Generated by Django 6.0.3 on 2026-07-05 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0003_student_batch_section'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='section',
            field=models.CharField(blank=True, help_text='Batch label e.g. Blue/Grey', max_length=50, null=True),
        ),
    ]
