# Generated by Django 6.0.3 on 2026-07-05 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0004_alter_student_section'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='section',
            field=models.CharField(blank=True, help_text='Denormalized label from batch_section; kept for legacy reads.', max_length=50, null=True),
        ),
    ]
