# Generated by Django 6.0.3 on 2026-08-05 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0008_student_graduation_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprofile',
            name='profile_locked',
            field=models.BooleanField(default=False),
        ),
    ]
