# Generated by Django 6.0.3 on 2026-08-08 17:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0009_studentprofile_profile_locked'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentprofile',
            name='previous_university',
        ),
    ]
