"""All Campus360 API routes for smoke/RBAC testing. Placeholder IDs = 1."""

PUBLIC_GET = [
    '/api/admissions/settings/',
]

PUBLIC_POST = [
    ('POST', '/api/auth/login/', {'email': 'nobody@test.edu', 'password': 'wrong'}),
    ('POST', '/api/auth/register/', {}),
    ('POST', '/api/auth/password-reset/request/', {'email': 'nobody@test.edu'}),
]

AUTH_GET = [
    '/api/auth/me/',
    '/api/auth/sessions/',
    '/api/roles/',
    '/api/permissions/',
    '/api/role-permissions/',
    '/api/audit-logs/',
    '/api/admissions/profile/',
    '/api/admissions/academic/list/',
    '/api/admissions/application/',
    '/api/admissions/documents/',
    '/api/admissions/challan/download/',
    '/api/admissions/admin/applications/',
    '/api/admissions/admin/settings/',
    '/api/academics/departments/',
    '/api/academics/programs/',
    '/api/academics/semesters/',
    '/api/academics/semesters/current/',
    '/api/academics/courses/',
    '/api/academics/policy/',
    '/api/academics/offerings/',
    '/api/academics/offerings/me/',
    '/api/students/me/',
    '/api/students/me/degree-progress/',
    '/api/students/me/degree-audit/',
    '/api/students/me/transcript/',
    '/api/students/',
    '/api/students/academic-standing/',
    '/api/students/graduation-candidates/',
    '/api/faculty/',
    '/api/faculty/me/',
    '/api/faculty/designations/',
    '/api/faculty/course-assignments/',
    '/api/faculty/course-assignments/unassigned/',
    '/api/faculty/workload/',
    '/api/enrollments/me/',
    '/api/enrollments/',
    '/api/enrollments/repeat-requests/',
    '/api/enrollments/repeat-requests/admin/',
    '/api/enrollments/repeat-requests/failed/',
    '/api/enrollments/academic-progress/my-status/',
    '/api/enrollments/academic-progress/teacher-warnings/',
    '/api/examinations/exam-types/',
    '/api/examinations/grades/',
    '/api/examinations/',
    '/api/examinations/semester/status/',
    '/api/examinations/marks-lock-status/',
    '/api/examinations/final-grades/me/',
    '/api/examinations/results/me/',
    '/api/examinations/results/',
    '/api/examinations/marks-edit-requests/',
    '/api/examinations/offering-edit-requests/',
    '/api/attendance/',
    '/api/attendance/summary/me/',
    '/api/attendance/summary/',
    '/api/attendance/summary/export/',
    '/api/attendance/leaves/me/',
    '/api/attendance/leaves/teacher/',
    '/api/notifications/',
    '/api/notifications/announcements/',
    '/api/notifications/announcements/target-options/',
    '/api/notifications/types/',
    '/api/fees/structures/',
    '/api/fees/challans/',
    '/api/fees/challans/me/',
    '/api/fees/finance/dashboard/',
    '/api/complaints/categories/',
    '/api/complaints/me/',
    '/api/complaints/',
    '/api/dashboard/stats/',
    '/api/recommendations/results/',
]

AUTH_GET_WITH_ID = [
    '/api/roles/user/1/',
    '/api/roles/1/permissions/',
    '/api/admissions/academic/1/',
    '/api/admissions/application/1/',
    '/api/admissions/documents/1/',
    '/api/admissions/documents/1/download/',
    '/api/admissions/admin/applications/1/',
    '/api/admissions/admin/applications/1/documents/1/download/',
    '/api/academics/departments/1/',
    '/api/academics/programs/1/',
    '/api/academics/programs/1/courses/',
    '/api/academics/semesters/1/',
    '/api/academics/courses/1/',
    '/api/academics/program-courses/1/',
    '/api/academics/offerings/1/',
    '/api/academics/offerings/1/students/',
    '/api/students/1/',
    '/api/students/1/degree-audit/',
    '/api/students/1/transcript/',
    '/api/faculty/1/',
    '/api/faculty/course-assignments/1/',
    '/api/enrollments/repeat-requests/1/review/',
    '/api/examinations/1/',
    '/api/examinations/1/marks/',
    '/api/examinations/marks/1/',
    '/api/examinations/results/1/publish/',
    '/api/examinations/marks-edit-requests/1/review/',
    '/api/examinations/offering-edit-requests/1/review/',
    '/api/attendance/leaves/1/',
    '/api/notifications/1/read/',
    '/api/notifications/announcements/1/',
    '/api/fees/structures/1/',
    '/api/fees/challans/me/1/download/',
    '/api/complaints/1/',
    '/api/complaints/1/thread/',
    '/api/complaints/1/feedback/',
]

AUTH_POST = [
    ('POST', '/api/auth/logout/', {}),
    ('POST', '/api/auth/change-password/', {'old_password': 'x', 'new_password': 'y'}),
    ('POST', '/api/roles/assign/', {}),
    ('POST', '/api/admissions/academic/', {}),
    ('POST', '/api/admissions/application/', {}),
    ('POST', '/api/admissions/documents/upload/', {}),
    ('POST', '/api/enrollments/repeat-requests/', {}),
    ('POST', '/api/examinations/create/', {}),
    ('POST', '/api/examinations/1/marks/enter/', {'marks': []}),
    ('POST', '/api/attendance/mark/', {}),
    ('POST', '/api/attendance/leaves/submit/', {}),
    ('POST', '/api/complaints/submit/', {}),
    ('POST', '/api/recommendations/profile/update/', {}),
    ('PUT', '/api/recommendations/profile/update/', {}),
]

ADMIN_ONLY_SENSITIVE = [
    ('GET', '/api/admissions/admin/applications/'),
    ('GET', '/api/students/'),
    ('GET', '/api/fees/finance/dashboard/'),
    ('POST', '/api/academics/departments/create/', {}),
    ('POST', '/api/enrollments/academic-progress/promote/', {}),
]

STUDENT_FORBIDDEN = [
    ('GET', '/api/admissions/admin/applications/'),
    ('GET', '/api/fees/finance/dashboard/'),
    ('POST', '/api/academics/programs/create/', {}),
]

APPLICANT_FORBIDDEN = [
    ('GET', '/api/students/'),
    ('GET', '/api/admissions/admin/applications/'),
    ('GET', '/api/examinations/results/'),
]
