# Generated by Django 6.0.3 on 2026-06-26 00:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academics', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Designation',
            fields=[
                ('designation_id', models.AutoField(primary_key=True, serialize=False)),
                ('designation_title', models.CharField(max_length=100, unique=True)),
                ('designation_level', models.IntegerField(blank=True, null=True)),
                ('job_description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'designation',
            },
        ),
        migrations.CreateModel(
            name='EmployeeProfile',
            fields=[
                ('profile_id', models.AutoField(primary_key=True, serialize=False)),
                ('employee_id', models.IntegerField()),
                ('employee_type', models.CharField(choices=[('faculty', 'Faculty'), ('staff', 'Staff')], max_length=10)),
                ('cnic', models.CharField(max_length=15, unique=True)),
                ('date_of_birth', models.DateField()),
                ('gender', models.CharField(blank=True, max_length=10)),
                ('nationality', models.CharField(default='Pakistani', max_length=50)),
                ('phone_number', models.CharField(max_length=20)),
                ('emergency_contact_name', models.CharField(max_length=100)),
                ('emergency_contact_phone', models.CharField(max_length=20)),
                ('emergency_contact_relation', models.CharField(max_length=50)),
                ('current_address', models.TextField()),
                ('permanent_address', models.TextField(blank=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'employee_profile',
                'unique_together': {('employee_id', 'employee_type')},
            },
        ),
        migrations.CreateModel(
            name='Faculty',
            fields=[
                ('faculty_id', models.AutoField(primary_key=True, serialize=False)),
                ('employee_code', models.CharField(max_length=50, unique=True)),
                ('qualification', models.CharField(max_length=100)),
                ('specialization', models.CharField(blank=True, max_length=200)),
                ('joining_date', models.DateField()),
                ('employment_type', models.CharField(choices=[('permanent', 'Permanent'), ('visiting', 'Visiting'), ('contractual', 'Contractual')], max_length=30)),
                ('status', models.CharField(choices=[('active', 'Active'), ('on_leave', 'On Leave'), ('resigned', 'Resigned'), ('retired', 'Retired')], default='active', max_length=20)),
                ('office_floor', models.CharField(blank=True, max_length=20)),
                ('office_hours', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='faculty_members', to='academics.department')),
                ('designation', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='faculty_members', to='faculty.designation')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='faculty_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'faculty',
            },
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('staff_id', models.AutoField(primary_key=True, serialize=False)),
                ('employee_code', models.CharField(max_length=50, unique=True)),
                ('joining_date', models.DateField()),
                ('employment_type', models.CharField(choices=[('permanent', 'Permanent'), ('contractual', 'Contractual'), ('temporary', 'Temporary')], max_length=30)),
                ('status', models.CharField(choices=[('active', 'Active'), ('on_leave', 'On Leave'), ('resigned', 'Resigned'), ('retired', 'Retired')], default='active', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='staff_members', to='academics.department')),
                ('designation', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='staff_members', to='faculty.designation')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='staff_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'staff',
            },
        ),
    ]
