# Generated by Django 6.0.3 on 2026-07-05 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faculty', '0004_faculty_employment_contract'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeeprofile',
            name='employee_type',
            field=models.CharField(default='faculty', max_length=10),
        ),
        migrations.DeleteModel(
            name='Staff',
        ),
    ]
