# Generated by Django 6.0.3 on 2026-06-26 00:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academics', '0002_initial'),
        ('faculty', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Section',
            fields=[
                ('section_id', models.AutoField(primary_key=True, serialize=False)),
                ('section_name', models.CharField(max_length=5)),
                ('section_type', models.CharField(choices=[('theory', 'Theory'), ('lab', 'Lab'), ('theory_lab_combined', 'Theory + Lab Combined')], max_length=30)),
                ('max_capacity', models.IntegerField()),
                ('enrolled_count', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='academics.course')),
                ('faculty', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='sections', to='faculty.faculty')),
                ('semester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='academics.semester')),
            ],
            options={
                'db_table': 'section',
                'unique_together': {('course', 'semester', 'section_name')},
            },
        ),
        migrations.CreateModel(
            name='SectionSchedule',
            fields=[
                ('schedule_id', models.AutoField(primary_key=True, serialize=False)),
                ('day_of_week', models.CharField(choices=[('Monday', 'Monday'), ('Tuesday', 'Tuesday'), ('Wednesday', 'Wednesday'), ('Thursday', 'Thursday'), ('Friday', 'Friday'), ('Saturday', 'Saturday')], max_length=10)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('room_number', models.CharField(max_length=20)),
                ('building_name', models.CharField(blank=True, max_length=100)),
                ('schedule_type', models.CharField(choices=[('lecture', 'Lecture'), ('lab', 'Lab'), ('tutorial', 'Tutorial')], default='lecture', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='sections.section')),
            ],
            options={
                'db_table': 'section_schedule',
            },
        ),
    ]
