# Generated by Django 6.0.3 on 2026-06-28 10:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0002_initial'),
        ('sections', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BatchSection',
            fields=[
                ('batch_section_id', models.AutoField(primary_key=True, serialize=False)),
                ('section_name', models.CharField(max_length=50)),
                ('batch_year', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='batch_sections', to='academics.degreeprogram')),
            ],
            options={
                'db_table': 'batch_section',
                'unique_together': {('section_name', 'batch_year', 'program')},
            },
        ),
    ]
