# Generated by Django 6.0.3 on 2026-06-26 20:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academics', '0002_initial'),
        ('enrollments', '0001_initial'),
        ('faculty', '0001_initial'),
        ('sections', '0001_initial'),
        ('students', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ExamType',
            fields=[
                ('exam_type_id', models.AutoField(primary_key=True, serialize=False)),
                ('type_name', models.CharField(max_length=50, unique=True)),
                ('weightage_percentage', models.DecimalField(decimal_places=2, max_digits=5)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'db_table': 'exam_type',
            },
        ),
        migrations.CreateModel(
            name='Grade',
            fields=[
                ('grade_id', models.AutoField(primary_key=True, serialize=False)),
                ('grade_letter', models.CharField(max_length=5, unique=True)),
                ('min_percentage', models.DecimalField(decimal_places=2, max_digits=5)),
                ('max_percentage', models.DecimalField(decimal_places=2, max_digits=5)),
                ('grade_points', models.DecimalField(decimal_places=2, max_digits=3)),
                ('status', models.CharField(choices=[('pass', 'Pass'), ('fail', 'Fail')], max_length=10)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'db_table': 'grade_scale',
            },
        ),
        migrations.CreateModel(
            name='Examination',
            fields=[
                ('exam_id', models.AutoField(primary_key=True, serialize=False)),
                ('exam_name', models.CharField(max_length=200)),
                ('exam_date', models.DateField()),
                ('start_time', models.TimeField(blank=True, null=True)),
                ('end_time', models.TimeField(blank=True, null=True)),
                ('duration_minutes', models.IntegerField()),
                ('total_marks', models.DecimalField(decimal_places=2, max_digits=6)),
                ('passing_marks', models.DecimalField(decimal_places=2, max_digits=6)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='examinations', to='academics.course')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_examinations', to=settings.AUTH_USER_MODEL)),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='examinations', to='sections.section')),
                ('semester', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='examinations', to='academics.semester')),
                ('exam_type', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='examinations', to='examinations.examtype')),
            ],
            options={
                'db_table': 'examination',
            },
        ),
        migrations.CreateModel(
            name='ExamSchedule',
            fields=[
                ('schedule_id', models.AutoField(primary_key=True, serialize=False)),
                ('exam_date', models.DateField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('duration_minutes', models.IntegerField()),
                ('room_number', models.CharField(max_length=20)),
                ('building_name', models.CharField(blank=True, max_length=100)),
                ('student_count', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_exam_schedules', to=settings.AUTH_USER_MODEL)),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='examinations.examination')),
                ('invigilator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invigilated_exams', to='faculty.faculty')),
            ],
            options={
                'db_table': 'exam_schedule',
            },
        ),
        migrations.CreateModel(
            name='FinalGrade',
            fields=[
                ('final_grade_id', models.AutoField(primary_key=True, serialize=False)),
                ('total_obtained_marks', models.DecimalField(decimal_places=2, max_digits=6)),
                ('total_marks', models.DecimalField(decimal_places=2, max_digits=6)),
                ('percentage', models.DecimalField(decimal_places=2, max_digits=5)),
                ('status', models.CharField(choices=[('pass', 'Pass'), ('fail', 'Fail'), ('incomplete', 'Incomplete'), ('withdrawn', 'Withdrawn')], max_length=20)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='final_grades', to='academics.course')),
                ('registration', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='final_grades', to='enrollments.courseregistration')),
                ('semester', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='final_grades', to='academics.semester')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='final_grades', to='students.student')),
                ('verified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_grades', to=settings.AUTH_USER_MODEL)),
                ('grade', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='final_grades', to='examinations.grade')),
            ],
            options={
                'db_table': 'final_grade',
            },
        ),
        migrations.CreateModel(
            name='Result',
            fields=[
                ('result_id', models.AutoField(primary_key=True, serialize=False)),
                ('sgpa', models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True)),
                ('cgpa', models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True)),
                ('total_credit_hours_attempted', models.IntegerField(blank=True, null=True)),
                ('total_credit_hours_earned', models.IntegerField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pass', 'Pass'), ('fail', 'Fail'), ('incomplete', 'Incomplete'), ('probation', 'Probation')], max_length=20)),
                ('is_published', models.BooleanField(default=False)),
                ('published_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('published_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='published_results', to=settings.AUTH_USER_MODEL)),
                ('semester', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='results', to='academics.semester')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='students.student')),
            ],
            options={
                'db_table': 'result',
                'unique_together': {('student', 'semester')},
            },
        ),
        migrations.CreateModel(
            name='ResultApproval',
            fields=[
                ('approval_id', models.AutoField(primary_key=True, serialize=False)),
                ('approval_date', models.DateField(auto_now_add=True)),
                ('remarks', models.TextField(blank=True)),
                ('approved_by', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='approved_results', to=settings.AUTH_USER_MODEL)),
                ('result', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='approval', to='examinations.result')),
            ],
            options={
                'db_table': 'result_approval',
            },
        ),
        migrations.CreateModel(
            name='Marks',
            fields=[
                ('marks_id', models.AutoField(primary_key=True, serialize=False)),
                ('obtained_marks', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('is_absent', models.BooleanField(default=False)),
                ('remarks', models.TextField(blank=True)),
                ('entered_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(blank=True, null=True)),
                ('entered_by', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='entered_marks', to='faculty.faculty')),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='marks', to='examinations.examination')),
                ('modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='modified_marks', to=settings.AUTH_USER_MODEL)),
                ('registration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='marks', to='enrollments.courseregistration')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='marks', to='students.student')),
            ],
            options={
                'db_table': 'marks',
                'unique_together': {('exam', 'student')},
            },
        ),
    ]
