# Generated by Django 6.0.3 on 2026-07-05 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('examinations', '0004_marks_period_and_exam_permission'),
    ]

    operations = [
        migrations.AlterField(
            model_name='markseditpermission',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='markseditpermission',
            name='request_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20),
        ),
    ]
