# Generated by Django 6.0.3 on 2026-07-05 16:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enrollments', '0001_initial'),
        ('examinations', '0005_alter_markseditpermission_is_active_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='finalgrade',
            name='registration',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='final_grade', to='enrollments.courseregistration'),
        ),
    ]
