# Generated by Django 6.0.3 on 2026-08-08 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('examinations', '0008_examination_weight_percentage_offeringmarkseditrequest'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='examination',
            name='duration_minutes',
        ),
        migrations.RemoveField(
            model_name='examination',
            name='end_time',
        ),
        migrations.RemoveField(
            model_name='examination',
            name='start_time',
        ),
        migrations.AddField(
            model_name='examination',
            name='assessment_category',
            field=models.CharField(choices=[('quiz', 'Quiz'), ('assignment', 'Assignment'), ('presentation', 'Presentation / Project'), ('mid_term', 'Mid Term'), ('final', 'Final Term')], default='quiz', max_length=20),
        ),
        migrations.AlterField(
            model_name='examination',
            name='exam_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='examination',
            name='weight_percentage',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Weight toward final grade. Mid=30, Final=40, continuous categories max 10% each.', max_digits=5, null=True),
        ),
        migrations.DeleteModel(
            name='ExamSchedule',
        ),
    ]
