# Generated by Django 6.0.3 on 2026-08-08 17:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('enrollments', '0003_repeatcourserequest'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='courseregistration',
            name='drop_reason',
        ),
        migrations.RemoveField(
            model_name='courseregistration',
            name='dropped_date',
        ),
    ]
