# Generated by Django 6.0.3 on 2026-08-08 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enrollments', '0004_cleanup_workflow_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='courseregistration',
            name='registration_type',
            field=models.CharField(choices=[('regular', 'Regular'), ('repeat', 'Repeat'), ('prerequisite_repeat', 'Prerequisite Repeat')], default='regular', max_length=30),
        ),
    ]
