# Generated by Django 6.0.3 on 2026-08-08 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enrollments', '0005_policy_and_registration_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courseregistration',
            name='registration_type',
            field=models.CharField(choices=[('regular', 'Regular'), ('repeat', 'Repeat'), ('prerequisite_repeat', 'Prerequisite Repeat'), ('carried_forward', 'Carried Forward')], default='regular', max_length=30),
        ),
    ]
