# Generated by Django 6.0.3 on 2026-08-08 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enrollments', '0006_soft_prereq_and_carry_forward'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courseregistration',
            name='registration_type',
            field=models.CharField(choices=[('regular', 'Regular'), ('repeat', 'Repeat'), ('prerequisite_repeat', 'Prerequisite Repeat')], default='regular', max_length=30),
        ),
    ]
