# Generated by Django 6.0.3 on 2026-06-26 00:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academics', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AdmissionApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('application_number', models.CharField(max_length=50, unique=True)),
                ('admission_type', models.CharField(choices=[('Regular', 'Regular'), ('Lateral', 'Lateral'), ('Migration', 'Migration')], default='Regular', max_length=20)),
                ('session_year', models.IntegerField(blank=True, null=True)),
                ('session_type', models.CharField(blank=True, choices=[('spring', 'Spring'), ('fall', 'Fall'), ('summer', 'Summer')], max_length=20, null=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('pending', 'Pending'), ('under_review', 'Under Review'), ('documents_pending', 'Documents Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('waitlist', 'Waitlist'), ('registered', 'Registered')], default='pending', max_length=20)),
                ('is_fee_paid', models.BooleanField(default=False)),
                ('is_eligible', models.BooleanField(blank=True, null=True)),
                ('is_documents_verified', models.BooleanField(default=False)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='applications', to='academics.degreeprogram')),
            ],
            options={
                'db_table': 'admissions_application',
            },
        ),
        migrations.CreateModel(
            name='AdmissionDecision',
            fields=[
                ('decision_id', models.AutoField(primary_key=True, serialize=False)),
                ('decision', models.CharField(choices=[('approved', 'Approved'), ('rejected', 'Rejected'), ('waitlist', 'Waitlist')], max_length=20)),
                ('decision_date', models.DateField(auto_now_add=True)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('registration_deadline', models.DateField(blank=True, null=True)),
                ('offered_section', models.CharField(blank=True, max_length=20, null=True)),
                ('rejection_reason', models.TextField(blank=True, null=True)),
                ('merit_score', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('merit_position', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('application', models.OneToOneField(on_delete=django.db.models.deletion.RESTRICT, related_name='decision', to='admissions.admissionapplication')),
                ('decided_by', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='admission_decisions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'admissions_decision',
            },
        ),
        migrations.CreateModel(
            name='AdmissionLog',
            fields=[
                ('log_id', models.AutoField(primary_key=True, serialize=False)),
                ('action_type', models.CharField(choices=[('created', 'Created'), ('submitted', 'Submitted'), ('reviewed', 'Reviewed'), ('documents_verified', 'Documents Verified'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('waitlisted', 'Waitlisted'), ('registered', 'Registered')], max_length=50)),
                ('previous_status', models.CharField(blank=True, max_length=30, null=True)),
                ('new_status', models.CharField(blank=True, max_length=30, null=True)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='admissions.admissionapplication')),
                ('performed_by', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='admission_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'admissions_log',
            },
        ),
        migrations.CreateModel(
            name='Applicant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('father_name', models.CharField(blank=True, max_length=100)),
                ('cnic', models.CharField(blank=True, max_length=13)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('gender', models.CharField(blank=True, max_length=10)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('religion', models.CharField(blank=True, max_length=50)),
                ('nationality', models.CharField(default='Pakistani', max_length=50)),
                ('marital_status', models.CharField(blank=True, max_length=20)),
                ('perm_country', models.CharField(blank=True, max_length=50)),
                ('perm_state', models.CharField(blank=True, max_length=50)),
                ('perm_city', models.CharField(blank=True, max_length=50)),
                ('perm_address', models.TextField(blank=True)),
                ('emergency_name', models.CharField(blank=True, max_length=100)),
                ('emergency_relation', models.CharField(blank=True, max_length=50)),
                ('emergency_phone', models.CharField(blank=True, max_length=20)),
                ('guardian_name', models.CharField(blank=True, max_length=100)),
                ('guardian_cnic', models.CharField(blank=True, max_length=13)),
                ('guardian_relation', models.CharField(blank=True, max_length=50)),
                ('profile_image', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='applicant_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'admissions_applicant',
            },
        ),
        migrations.AddField(
            model_name='admissionapplication',
            name='applicant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='admissions.applicant'),
        ),
        migrations.CreateModel(
            name='AcademicRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('authority', models.CharField(max_length=200)),
                ('qualification_level', models.CharField(max_length=50)),
                ('qualification', models.CharField(max_length=200)),
                ('institute', models.CharField(max_length=200)),
                ('roll_number', models.CharField(blank=True, max_length=20)),
                ('start_year', models.IntegerField()),
                ('end_year', models.IntegerField()),
                ('grading_system', models.CharField(choices=[('marks', 'Marks'), ('cgpa', 'CGPA')], default='marks', max_length=10)),
                ('obtained', models.DecimalField(decimal_places=2, max_digits=7)),
                ('total', models.DecimalField(decimal_places=2, max_digits=7)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('applicant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='academic_records', to='admissions.applicant')),
            ],
            options={
                'db_table': 'admissions_academic_record',
            },
        ),
        migrations.CreateModel(
            name='ProgramPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('preference_order', models.IntegerField()),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='preferences', to='admissions.admissionapplication')),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='preferences', to='academics.degreeprogram')),
            ],
            options={
                'db_table': 'admissions_program_preference',
            },
        ),
        migrations.CreateModel(
            name='ApplicantDocument',
            fields=[
                ('document_id', models.AutoField(primary_key=True, serialize=False)),
                ('document_type', models.CharField(choices=[('cnic_front', 'CNIC Front'), ('cnic_back', 'CNIC Back'), ('domicile', 'Domicile'), ('photograph', 'Photograph'), ('matric_marksheet', 'Matric Marksheet'), ('matric_certificate', 'Matric Certificate'), ('inter_marksheet', 'Inter Marksheet'), ('inter_certificate', 'Inter Certificate')], max_length=50)),
                ('file_name', models.CharField(max_length=255)),
                ('file_path', models.CharField(max_length=500)),
                ('file_size', models.IntegerField()),
                ('file_type', models.CharField(max_length=50)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('is_verified', models.BooleanField(default=False)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('verification_remarks', models.TextField(blank=True)),
                ('applicant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='admissions.applicant')),
                ('verified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_documents', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'applicant_documents',
                'ordering': ['-uploaded_at'],
                'unique_together': {('applicant', 'document_type')},
            },
        ),
    ]
