# Generated by Django 6.0.3 on 2026-07-30 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admissions', '0004_remove_offered_section'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admissionlog',
            name='action_type',
            field=models.CharField(choices=[('created', 'Created'), ('submitted', 'Submitted'), ('reviewed', 'Reviewed'), ('documents_verified', 'Documents Verified'), ('challan_accepted', 'Challan Accepted'), ('challan_rejected', 'Challan Rejected'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('waitlisted', 'Waitlisted'), ('registered', 'Registered')], max_length=50),
        ),
    ]
