# Generated by Django 6.0.3 on 2026-08-09 05:38

from django.db import migrations, models


def dedupe_cnic_and_waitlist(apps, schema_editor):
    Applicant = apps.get_model('admissions', 'Applicant')
    AdmissionApplication = apps.get_model('admissions', 'AdmissionApplication')
    AdmissionDecision = apps.get_model('admissions', 'AdmissionDecision')

    seen = set()
    for applicant in Applicant.objects.exclude(cnic__isnull=True).exclude(cnic='').order_by('pk'):
        cnic = (applicant.cnic or '').strip()
        if not cnic:
            continue
        if cnic in seen:
            applicant.cnic = None
            applicant.save(update_fields=['cnic'])
        else:
            seen.add(cnic)

    AdmissionApplication.objects.filter(status='waitlist').update(status='under_review')
    AdmissionDecision.objects.filter(decision='waitlist').update(decision='rejected')


class Migration(migrations.Migration):

    dependencies = [
        ('admissions', '0006_admissionsettings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicant',
            name='cnic',
            field=models.CharField(blank=True, max_length=13, null=True),
        ),
        migrations.RunPython(dedupe_cnic_and_waitlist, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='admissionapplication',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('pending', 'Pending'), ('challan_pending', 'Challan Pending'), ('under_review', 'Under Review'), ('documents_pending', 'Documents Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('registered', 'Registered')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='admissiondecision',
            name='decision',
            field=models.CharField(choices=[('approved', 'Approved'), ('rejected', 'Rejected')], max_length=20),
        ),
        migrations.AlterField(
            model_name='admissionlog',
            name='action_type',
            field=models.CharField(choices=[('created', 'Created'), ('submitted', 'Submitted'), ('reviewed', 'Reviewed'), ('documents_verified', 'Documents Verified'), ('challan_accepted', 'Challan Accepted'), ('challan_rejected', 'Challan Rejected'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('registered', 'Registered')], max_length=50),
        ),
        migrations.AlterField(
            model_name='applicant',
            name='cnic',
            field=models.CharField(blank=True, max_length=13, null=True, unique=True),
        ),
    ]
