# Generated by Django 6.0.3 on 2026-06-26 00:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academics', '0001_initial'),
        ('faculty', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='hod',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='headed_department', to='faculty.faculty'),
        ),
        migrations.AddField(
            model_name='degreeprogram',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='programs', to='academics.department'),
        ),
        migrations.AddField(
            model_name='course',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='courses', to='academics.department'),
        ),
        migrations.AddField(
            model_name='programcourse',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='program_courses', to='academics.course'),
        ),
        migrations.AddField(
            model_name='programcourse',
            name='program',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='program_courses', to='academics.degreeprogram'),
        ),
        migrations.AlterUniqueTogether(
            name='programcourse',
            unique_together={('program', 'course', 'semester_number')},
        ),
    ]
