# Generated by Django 6.0.3 on 2026-07-05 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0005_semester_marks_dates'),
    ]

    operations = [
        migrations.AlterField(
            model_name='programcourseprerequisite',
            name='or_group',
            field=models.PositiveSmallIntegerField(default=0, help_text='Same or_group on one course = OR; different groups = AND'),
        ),
    ]
