# Generated by Django 6.0.3 on 2026-07-30 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0008_migrate_sections_to_offerings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courseofferingschedule',
            name='day_of_week',
            field=models.CharField(choices=[('Monday', 'Monday'), ('Tuesday', 'Tuesday'), ('Wednesday', 'Wednesday'), ('Thursday', 'Thursday'), ('Friday', 'Friday'), ('Saturday', 'Saturday')], max_length=10),
        ),
        migrations.AlterField(
            model_name='courseofferingschedule',
            name='schedule_type',
            field=models.CharField(choices=[('lecture', 'Lecture'), ('lab', 'Lab'), ('tutorial', 'Tutorial')], default='lecture', max_length=20),
        ),
    ]
