# Generated by Django 6.0.3 on 2026-08-08 17:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0010_academicpolicy'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='courseoffering',
            name='max_capacity',
        ),
        migrations.RemoveField(
            model_name='semester',
            name='registration_end_date',
        ),
        migrations.RemoveField(
            model_name='semester',
            name='registration_start_date',
        ),
        migrations.DeleteModel(
            name='CourseOfferingSchedule',
        ),
    ]
