# Generated by Django 6.0.3 on 2026-08-08 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0011_cleanup_workflow_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='academicpolicy',
            name='allow_concurrent_prerequisite_enrollment',
            field=models.BooleanField(default=True, help_text='If credit cap allows, enroll blocked course alongside its in-progress prerequisite repeat.'),
        ),
        migrations.AddField(
            model_name='academicpolicy',
            name='auto_enroll_failed_prerequisites',
            field=models.BooleanField(default=True, help_text='When a course is blocked, auto-enroll failed prerequisite courses as repeats.'),
        ),
        migrations.AddField(
            model_name='academicpolicy',
            name='max_repeat_credit_hours',
            field=models.IntegerField(default=21, help_text='Maximum credit hours for admin-approved repeat requests.'),
        ),
        migrations.AddField(
            model_name='academicpolicy',
            name='max_semester_credit_hours',
            field=models.IntegerField(default=21, help_text='Maximum credit hours a student may register in one semester.'),
        ),
        migrations.AddField(
            model_name='academicpolicy',
            name='min_attendance_percentage',
            field=models.DecimalField(decimal_places=2, default=75.0, help_text='Minimum attendance % before shortage warnings are sent.', max_digits=5),
        ),
    ]
