# Generated by Django 6.0.3 on 2026-08-08 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0012_policy_and_registration_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='academicpolicy',
            name='carry_forward_missed_courses',
            field=models.BooleanField(default=True, help_text='On promotion, carry unregistered curriculum courses from the completed semester forward.'),
        ),
        migrations.AddField(
            model_name='academicpolicy',
            name='soft_prerequisite_enrollment',
            field=models.BooleanField(default=True, help_text='Enroll curriculum courses with prerequisite warnings instead of deferring (keeps batch together).'),
        ),
    ]
