# Generated by Django 6.0.3 on 2026-08-08 19:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0013_soft_prereq_and_carry_forward'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='academicpolicy',
            name='carry_forward_missed_courses',
        ),
    ]
