# Generated by Django 6.0.3 on 2026-08-12 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0018_courseoffering_cohort_sequence'),
    ]

    operations = [
        migrations.AlterField(
            model_name='academicpolicy',
            name='min_sgpa_pass',
            field=models.DecimalField(decimal_places=2, default=2.0, help_text='Minimum SGPA for semester pass standing (independent of individual course fails).', max_digits=3),
        ),
        migrations.AlterField(
            model_name='academicpolicy',
            name='min_sgpa_probation',
            field=models.DecimalField(decimal_places=2, default=2.0, help_text='Minimum SGPA to avoid semester fail; below min_sgpa_pass but above this yields probation.', max_digits=3),
        ),
    ]
