# Generated by Django 6.0.3 on 2026-08-08 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complaints', '0002_complaint_admin_response'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='complaint',
            name='attachments',
        ),
        migrations.RemoveField(
            model_name='complaint',
            name='priority',
        ),
        migrations.AlterField(
            model_name='complaint',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('resolved', 'Resolved'), ('closed', 'Closed'), ('rejected', 'Rejected')], default='pending', max_length=30),
        ),
        migrations.DeleteModel(
            name='ComplaintAssignment',
        ),
    ]
