# Generated by Django 6.0.3 on 2026-06-26 20:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academics', '0002_initial'),
        ('enrollments', '0001_initial'),
        ('faculty', '0001_initial'),
        ('sections', '0001_initial'),
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('attendance_id', models.AutoField(primary_key=True, serialize=False)),
                ('attendance_date', models.DateField()),
                ('lecture_number', models.IntegerField(blank=True, null=True)),
                ('topic_covered', models.TextField(blank=True)),
                ('marked_at', models.DateTimeField(auto_now_add=True)),
                ('marked_by', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='marked_attendances', to='faculty.faculty')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendances', to='sections.section')),
            ],
            options={
                'db_table': 'attendance',
                'unique_together': {('section', 'attendance_date', 'lecture_number')},
            },
        ),
        migrations.CreateModel(
            name='AttendanceRecord',
            fields=[
                ('record_id', models.AutoField(primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('present', 'Present'), ('absent', 'Absent'), ('late', 'Late'), ('leave', 'Leave'), ('excused', 'Excused')], max_length=20)),
                ('remarks', models.TextField(blank=True)),
                ('attendance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='records', to='attendance.attendance')),
                ('registration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_records', to='enrollments.courseregistration')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_records', to='students.student')),
            ],
            options={
                'db_table': 'attendance_record',
                'unique_together': {('attendance', 'student')},
            },
        ),
        migrations.CreateModel(
            name='StudentAttendanceSummary',
            fields=[
                ('summary_id', models.AutoField(primary_key=True, serialize=False)),
                ('total_lectures', models.IntegerField(default=0)),
                ('attended_lectures', models.IntegerField(default=0)),
                ('late_count', models.IntegerField(default=0)),
                ('leave_count', models.IntegerField(default=0)),
                ('attendance_percentage', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('is_below_threshold', models.BooleanField(default=False)),
                ('last_updated_at', models.DateTimeField(auto_now=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='attendance_summaries', to='academics.course')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='attendance_summaries', to='sections.section')),
                ('semester', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='attendance_summaries', to='academics.semester')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_summaries', to='students.student')),
            ],
            options={
                'db_table': 'student_attendance_summary',
                'unique_together': {('student', 'section')},
            },
        ),
    ]
