# Generated by Django 6.0.3 on 2026-08-08 17:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0004_leave_offering_optional'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentattendancesummary',
            name='late_count',
        ),
    ]
