# Generated by Django 6.0.3 on 2026-08-08 17:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fees', '0002_delete_scholarship'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feestructure',
            name='effective_to',
        ),
        migrations.DeleteModel(
            name='Payment',
        ),
    ]
