# Generated by Django 6.0.3 on 2026-08-09 05:38

from django.db import migrations, models


def normalize_partial_challans(apps, schema_editor):
    Challan = apps.get_model('fees', 'Challan')
    Challan.objects.filter(status='partial').update(status='pending')


class Migration(migrations.Migration):

    dependencies = [
        ('fees', '0003_cleanup_workflow_fields'),
    ]

    operations = [
        migrations.RunPython(normalize_partial_challans, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='challan',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('paid', 'Paid'), ('overdue', 'Overdue')], default='pending', max_length=20),
        ),
    ]
