# Generated by Django 6.0.3 on 2026-08-09 06:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academics', '0014_remove_carry_forward'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CareerGoal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'db_table': 'recommendation_career_goal',
            },
        ),
        migrations.CreateModel(
            name='Interest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'db_table': 'recommendation_interest',
            },
        ),
        migrations.CreateModel(
            name='RecommendationProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('educational_background', models.CharField(blank=True, choices=[('FSc Pre-Medical', 'FSc Pre-Medical'), ('FSc Pre-Engineering', 'FSc Pre-Engineering'), ('ICS Physics', 'ICS Physics'), ('ICS Statistics', 'ICS Statistics'), ('ICS Economics', 'ICS Economics'), ('ICom', 'ICom'), ('FA Arts / Humanities', 'FA Arts / Humanities')], max_length=50)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='recommendation_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'recommendation_profile',
            },
        ),
        migrations.CreateModel(
            name='RecommendationResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('match_score', models.FloatField()),
                ('reasons', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recommendations', to='recommendation.recommendationprofile')),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academics.degreeprogram')),
            ],
            options={
                'db_table': 'recommendation_result',
                'ordering': ['-match_score'],
            },
        ),
        migrations.CreateModel(
            name='DegreeEligibility',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('background', models.CharField(choices=[('FSc Pre-Medical', 'FSc Pre-Medical'), ('FSc Pre-Engineering', 'FSc Pre-Engineering'), ('ICS Physics', 'ICS Physics'), ('ICS Statistics', 'ICS Statistics'), ('ICS Economics', 'ICS Economics'), ('ICom', 'ICom'), ('FA Arts / Humanities', 'FA Arts / Humanities')], max_length=50)),
                ('degree', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eligible_backgrounds', to='academics.degreeprogram')),
            ],
            options={
                'db_table': 'recommendation_degree_eligibility',
                'unique_together': {('background', 'degree')},
            },
        ),
        migrations.CreateModel(
            name='ProfileInterest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recommendation.interest')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interests', to='recommendation.recommendationprofile')),
            ],
            options={
                'db_table': 'recommendation_profile_interest',
                'unique_together': {('profile', 'interest')},
            },
        ),
        migrations.CreateModel(
            name='ProfileGoal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('goal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recommendation.careergoal')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='goals', to='recommendation.recommendationprofile')),
            ],
            options={
                'db_table': 'recommendation_profile_goal',
                'unique_together': {('profile', 'goal')},
            },
        ),
        migrations.CreateModel(
            name='SubjectMark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject_name', models.CharField(max_length=100)),
                ('marks_obtained', models.FloatField()),
                ('total_marks', models.FloatField(default=200)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='marks', to='recommendation.recommendationprofile')),
            ],
            options={
                'db_table': 'recommendation_subject_mark',
                'unique_together': {('profile', 'subject_name')},
            },
        ),
        migrations.CreateModel(
            name='TrendScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('background', models.CharField(choices=[('FSc Pre-Medical', 'FSc Pre-Medical'), ('FSc Pre-Engineering', 'FSc Pre-Engineering'), ('ICS Physics', 'ICS Physics'), ('ICS Statistics', 'ICS Statistics'), ('ICS Economics', 'ICS Economics'), ('ICom', 'ICom'), ('FA Arts / Humanities', 'FA Arts / Humanities')], max_length=50)),
                ('score', models.IntegerField(help_text='Score between 0 and 10')),
                ('degree', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recommendation_trends', to='academics.degreeprogram')),
            ],
            options={
                'db_table': 'recommendation_trend_score',
                'unique_together': {('background', 'degree')},
            },
        ),
    ]
